services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    container_name: keycloak_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak: